### ISSUE TITLE
FW 9.00GOLD

### ISSUE THREAD

**Issue by AlexanderQueen** [KAR0218/KAR0218.github.io#1]
Hi. Why in your rep and page isn't 9.00 Gold?

**Comment by KAR0218** [comment]
Hi, 900Gold host worked juat on http
Unfortunately github have https
use it just on this link
http://karo218.ir/900

**Comment by AlexanderQueen** [comment]
@KAR0218 Thx for replying. I find why it "http" and not working on "https". Thx
