### ISSUE TITLE
Host 9.00 goldhen

### ISSUE THREAD

**Issue by IRONB0SS** [KAR0218/KAR0218.github.io#6]
سلام آقای شریفی، خوب هستید
هاست ۹.۰۰ گلدهنی که به تازگی بروزش کردید، مشکل داره
روی jailbreaking....wait میمونه بعدش فقط ارور حافظه میاد یا this page is not responding میزنه
تو مرحله سوم jailbreaking...wait ارور مموری میاد
 ```
 await sleep(0);
    await double_free(s1);
    debug_log('Jailbreaking........... Wait');
    await triple_free(s1, jsview, view_leak_arr, view_leak);
```

در واقع از مرحله دوم به سوم سوییچ نمیشه اصلا
![20240207_020401](https://github.com/KAR0218/KAR0218.github.io/assets/97769328/d13a87cd-6013-4328-851f-ef0da4302dde)

ویرایش : خب از cache.manifest همه رو بجز index.html پاک کردم و اوکی شد

![Screenshot 2024-02-07 021100](https://github.com/KAR0218/KAR0218.github.io/assets/97769328/cee7b6e7-f8ed-4aa1-bbfe-bd6ac6c9f72a)

همه اینایی که بالاست رو به cache.manifest برگردوندم و مشکل برگشت

ویرایش دوم :
![image](https://github.com/KAR0218/KAR0218.github.io/assets/97769328/a54ccabf-e54b-4d58-abe0-d870e6c5d07d)

این 0x000 هم تو هاست esp32 هستش که بنظرم باگه

دقیقا بجای مرحله سوم jailbreaking....wait ارور بالایی رو نشون میده

```
await sleep(0);
   await double_free(s1);
   debug_log('Jailbreaking........... Wait');
   await triple_free(s1, jsview, view_leak_arr, view_leak);
```

**Comment by KAR0218** [comment]
سلام، ممنونم. دوباره تستش کنید ببین درست شده. قبلش کلیر کش و کوکی یادت نره

**Comment by IRONB0SS** [comment]
‏سلام چشم الان تست میکنم

**Comment by IRONB0SS** [comment]
سلام مجدد، هاست رو حدودا 20 بار تست کردم، 10 بار با کد alert Webkit done و 10 بار هم بدون کد

`alert('Webkit Done!!!... Click ok');`

هر 20 بار هم اوکی بود و بدون مشکل گلدهن فعال شد فقط **بعضی وقتا**، بازم تو قبل مرحله  سوم jailbreaking....wiating ارور مموری مثلا 3 بار پشت سر هم میومد (دقیقا از ۳ تا بیشتر نمیشه یا کلا ارور نمیاد و یا هم که میاد دقیقا یکبار یا ۳بار میاد) قبلا کلا رد نمیشد اما الان حداکثر بعد از ۳ ارور رد میشه از این مرحله

و اما هاست esp32 یه ارور دیگه هم پیدا کردم
![20240208142348](https://github.com/KAR0218/KAR0218.github.io/assets/97769328/216b58fa-2cae-4030-979f-48f51ac4beea)


بعد آقای شریفی اگه سورس کد فایل esp32 رو داشته باشم، با این دستور به bin میتونم تبدیلش کنم؟
![image](https://github.com/KAR0218/KAR0218.github.io/assets/97769328/3635dfa9-8fc6-4aab-883c-25b9e7362498)

بابت زحمات و وقتتون متشکرم

**Comment by al10capote** [comment]
Please share the Index.html
